# Generated by Django 4.2.13 on 2024-05-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_mesa', '0002_tipo_procedimiento_solicitud_caso_solucion_caso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='caso_codigo',
            field=models.CharField(db_comment='codigo del caso, irrepetible', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='caso_estado',
            field=models.CharField(choices=[('solicitada', 'solicitada'), ('en proceso', 'en proseso'), ('finalizado', 'finalizado')], db_comment='', default='solicitada', max_length=15),
        ),
    ]
