# Generated by Django 4.2.13 on 2024-06-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_mesa', '0003_alter_caso_caso_codigo_alter_caso_caso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='fecha_hora_actualizacion',
            field=models.DateField(auto_now=True, db_comment=''),
        ),
        migrations.AlterField(
            model_name='ofi_ambientes',
            name='fecha_hora_actualizacion',
            field=models.DateField(auto_now=True, db_comment=''),
        ),
        migrations.AlterField(
            model_name='ofi_ambientes',
            name='fecha_hora_creacion',
            field=models.DateField(auto_now_add=True, db_comment=''),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_hora_actualizacion',
            field=models.DateField(auto_now=True, db_comment=''),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_hora_creacion',
            field=models.DateField(auto_now_add=True, db_comment=''),
        ),
        migrations.AlterField(
            model_name='solucion_caso',
            name='fecha_hora_actualizacion',
            field=models.DateField(auto_now=True, db_comment=''),
        ),
        migrations.AlterField(
            model_name='solucion_caso',
            name='fecha_hora_creacion',
            field=models.DateField(auto_now_add=True, db_comment=''),
        ),
        migrations.AlterField(
            model_name='tipo_procedimiento',
            name='fecha_hora_actualizacion',
            field=models.DateField(auto_now=True, db_comment=''),
        ),
        migrations.AlterField(
            model_name='tipo_procedimiento',
            name='fecha_hora_creacion',
            field=models.DateField(auto_now_add=True, db_comment=''),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_hora_actualizacion',
            field=models.DateField(auto_now=True, db_comment=''),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_hora_creacion',
            field=models.DateField(auto_now_add=True, db_comment=''),
        ),
    ]
